config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users' => 'home#users'
  get '/profile/:id' => 'home#profile'

  post '/follow' => 'home#follow'
  post '/unfollow' => 'home#unfollow'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  end

  root to: "posts#index"

  mount Resque::Server, :at => '/resque'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
  validates :content, presence: true
  acts_as_votable
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # before_action :set_comment, only: [:update, :destroy]


  # POST /comments
  # POST /comments.json
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(params[:comment].permit(:content))
    @comment.user_id = current_user.id
    @comment.save
    # redirect_to post_path(@post)
    respond_to do |format|
      format.html {
        redirect_to @post
        flash[:success] = 'Comment posted.'
      }
      format.js{
        flash[:success] = 'Comment posted.'
      }
    end
  end


  # DELETE /comments/1
  # DELETE /comments/1.json
  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.html{
        redirect_to post_path(@post)
        flash[:success] = 'Comment deleted.'
      }
      format.js{
        flash[:success] = 'Comment deleted.'
      }
    end
  end

  def upvote
    @comment = Comment.find(params[:id])
    @comment.upvote_by current_user
    respond_to do |format|
      format.html {
        redirect_to :back
      }
      format.js   { render :layout => false }
    end
  end

  def downvote
    @comment = Comment.find(params[:id])
    @comment.downvote_by current_user
    respond_to do |format|
      format.html {
        redirect_to :back
      }
      format.js   { render :layout => false }
    end
  end

  private
    def comment_params
      params.require(:comment).permit(:content)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div class="bubble-list">
  <div class="bubble clearfix">
    <%= link_to (image_tag comment.user.image.url(:small)), '/profile/' + comment.user.id.to_s %>
    <div class="bubble-content">
      <div class="point"></div>
      <p id="comment-font"><%= comment.content %></p>
      <br>

      <%# if user_signed_in? %>
          <%= link_to dislike_post_comment_path(post, comment),class: "dislike-comment", method: :put, remote: true do %>
              <i class="fa fa-thumbs-o-down" aria-hidden="true"></i>
              <span class="dislike-comment-count-<%= comment.id %>">
                <%= comment.get_downvotes.size %></span>
          <% end %>
          <%= link_to like_post_comment_path(post, comment),class: "like-comment" , method: :put, remote: true do %>
              <i class="fa fa-thumbs-o-up" aria-hidden="true"></i>
              <span class="like-comment-count-<%= comment.id %>">
                <%= comment.get_upvotes.size %></span>
          <% end %>

      <% #end %>
      <br>
      <small><%= time_ago_in_words(comment.created_at) %> Ago</small>
      <small style="float: right"><%= User.find(comment.user_id).email %></small>

      <% if user_signed_in? %>
          <% if User.find(comment.user_id) == current_user %>
              <h5><%= link_to 'Delete', [comment.post, comment], method: :delete,remote: true, data: {confirm: 'Are you sure?'} %></h5>
          <% end %>
      <% end %>

    </div>
  </div>
</div>

app/views/comments/_form.html.erb
<br>
<% if user_signed_in? %>
<h2 class="add-comment">Add a comment..</h2>
<%= form_for([@post, @post.comments.build], remote: true) do |f| %>

    <%= f.text_area :content, rows: 5, class:"text-area" %>

    <%= f.button class:"button2" %>
<% end %>
<% end %>

app/views/comments/create.js.erb
//    console.log();
    $('.comment_count').text('<%= @post.comments.size %> Comments');
//    console.log();
//    $('#comment-content').append('<%#=escape_javascript render 'comments/comment', :post => @post, :comment => @comment %>');
    $('#comment-content').html("<%=escape_javascript render @post.comments, post: @post %>");
    $('.text-area').val("");
<%= add_gritter("Comment Posted..", title: "NOTIFICATION", sticky: false, time: 1500, image: :success) %>

app/views/comments/destroy.js.erb
$('#comment-content').html("<%=escape_javascript render @post.comments, post: @comment.post %>");
$('.comment_count').html('<%= escape_javascript(pluralize(@post.comments.count, 'Comment')) %>');
<%= add_gritter("Comment Deleted..", title: "NOTIFICATION", sticky: false, time: 1500, image: :success) %>

app/views/comments/downvote.js.erb
$('.dislike-comment').bind('ajax:success', function() {

    $('.like-comment-count-<%= @comment.id %>').text(<%= @comment.get_upvotes.size%>);
    $('.dislike-comment-count-<%= @comment.id %>').text(<%= @comment.get_downvotes.size%>);

});

app/views/comments/upvote.js.erb
$('.like-comment').bind('ajax:success', function() {

    $('.like-comment-count-<%= @comment.id %>').text(<%= @comment.get_upvotes.size%>);
    $('.dislike-comment-count-<%= @comment.id %>').text(<%= @comment.get_downvotes.size%>);

});