config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  get '/users' => 'home#users'
  get '/profile/:id' => 'home#profile'

  post '/follow' => 'home#follow'
  post '/unfollow' => 'home#unfollow'

  resources :posts do
    member do
      put "like", to: "posts#upvote"
      put "dislike", to: "posts#downvote"
    end
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  end

  root to: "posts#index"

  mount Resque::Server, :at => '/resque'

end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true, length: {within: 5..80}
  validates :body, presence: true, length: {within: 10..50000}
  belongs_to :user
  has_many :comments, dependent: :destroy
  acts_as_votable

  has_attached_file :image, styles: { medium: "600x400#", thumb: "350x250#" }, :default_url => ActionController::Base.helpers.asset_path("placeholder-image.png")
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! ,except: [:show, :index]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all.order('created_at DESC').paginate(:page => params[:page], :per_page => 6)
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html {
        redirect_to posts_url, notice: 'Post was successfully destroyed.'
      }
      format.json { head :no_content }
    end
  end

  def upvote
    @post = Post.find(params[:id])
    @post.upvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @post.liked_count } }
      format.js   { render :layout => false }
    end
  end

  def downvote
    @post = Post.find(params[:id])
    @post.downvote_by current_user
    respond_to do |format|
      format.html {redirect_to :back }
      format.json { render json: { count: @post.liked_count } }
      format.js   { render :layout => false }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<br>
<%= form_for @post, html: {multipart: true} do |f| %>
    <% if @post.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

          <ul>
            <% @post.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>
    <div class="field">
      ADD THUMBNAIL<br>
      <%= f.file_field :image, class: "button-img" %>
    </div>
    <br><br>
    <div class="field">
      <%= f.text_area :title, class: "post-title", rows: 10, placeholder: "Title of your story..." %>
    </div>
    <div class="field">
      <br>
      <%= f.text_area :body, id:"trumbowyg", rows: 30, placeholder: "Content goes here..." %>
    </div>
    <div class="actions">
      <%= f.button %>
    </div>
<% end %>

<script>
    $('#trumbowyg').trumbowyg({
        svgPath: '<%= image_path("icons.svg")%>'
    });

</script>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
<div class="post">
  <div class="image"><%= link_to (image_tag post.image.url(:medium)), post %></div>
  <h2 id="title"><%= link_to post.title.capitalize, post %></h2>

  <hr>
  <div id="content">
    <span><%=h truncate(Nokogiri::HTML.parse(post.body).css('p').text, :length => 200) %> <%= link_to "READ MORE", post, {:style => 'text-decoration: none; color: green;'}%></span>
  </div>
  <hr>

  <div class="row1">
            <span>
              <div id="user_image_posts_index">
      <%= link_to (image_tag post.user.image.url(:small)), '/profile/' + post.user.id.to_s %>
    </div>
              <%= link_to post.user.name.capitalize, '/profile/' + post.user.id.to_s, {:style => 'text-decoration: none; color: brown; padding:10px;'}%>
            </span>
    <span>
              <i class="fa fa-comments-o"></i>
      <%= post.comments.count %>

      <i class="fa fa-heart" aria-hidden="true"></i>
      <%= post.get_upvotes.size %>
            </span>
  </div>
  <br style="line-height: 200%;">

  <div class="time">--
    <%= time_ago_in_words(post.created_at) %> ago
  </div>
</div>
<% end %>

app/views/posts/downvote.js.erb
$('.dislike').bind('ajax:success', function() {
    $('.like_count-<%= @post.id %>').text(<%= @post.get_upvotes.size%>);
    $('.dislike_count-<%= @post.id %>').text(<%= @post.get_downvotes.size%>);
    <%= add_gritter("_", title: "Post Disliked", sticky: false, time: 1500, image: :success) %>
});

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

app/views/posts/index.html.erb
<div class="main_body">
  <% if user_signed_in? %>
      <p id="intro">
        Hello
        <%= current_user.name.titleize %>
        <br>
        <span>
          What's new today.. Share your story
        </span>
      </p>
  <% else %>
      <p id="intro">
        What's new today..
        <br>
        <span>
          You need to Register or Login to post.
        </span>
      </p>
  <% end %>
  <br>
  <br>

  <div id="posts">
    <%= render partial: 'posts' %>
  </div>
  <%= will_paginate @posts%>
</div>

app/views/posts/index.js.erb
$('#posts').append('<%= escape_javascript(render partial: 'posts') %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= escape_javascript(will_paginate(@posts)) %>');
<% else %>
  $('.pagination').remove();
<% end %>
<% sleep(0.8) %>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="content-box">
  <div class="user-content">
    <div class="usr-img">
      <%= link_to (image_tag @post.user.image.url(:small)), '/profile/' + @post.user.id.to_s %>
    </div>
    <div class="other-details">
      <span class="user-name">
        <%= @post.user.name.upcase %>
      </span><span class="follow-link">
      <%= render 'home/follow', user: @post.user %>
    </span>
      <br>
      <br>
      <div class="cr-time">
        <%= @post.created_at.strftime("%d %B %Y") %>
      </div>
    </div>

    <p id="edit-del">
    <span>
    <% if @post.user == current_user %>
          <%= link_to 'Edit', edit_post_path(@post) %> |
          <%= link_to 'Delete', post_path(@post), method: :delete, data: {confirm: 'Are you sure?'} %>
    <% end %>
  </span>
    </p>

    <br>
  </div>
  <br>
  <hr class="hr-asdf">
  <br>
  <h1 class="title"><%= @post.title.capitalize %></h1>
  <br><br>
  <p class="body"><%= simple_format(@post.body, {}, :sanitize => false) %></p>
  <br>
  <br>
  <hr class="hr-asdf">


  <aside class="vote-count bind-<%= @post.id %>">
    <%= link_to like_post_path(@post), method: :put, remote: true, class: 'like' do %>
        <i class="fa fa-angle-double-up"></i>
        <span class="like_count-<%= @post.id %>"><%= @post.get_upvotes.size %></span>
    <% end %>
    <%= link_to dislike_post_path(@post), method: :put, remote: true, class: 'dislike' do %>
        <i class="fa fa-angle-double-down"></i>
        <span class="dislike_count-<%= @post.id %>"><%= @post.get_downvotes.size %></span>
    <% end %>
  </aside>

</div>

<br><br><br>
<div id="comments">
  <h2 style="font-family: Palatino; color: lightslategray;" class="comment_count"><%= pluralize(@post.comments.count, 'Comment') %></h2>
  <br>
  <hr>
  <div id="comments-info">
    <div id="comment-content">
      <%= render @post.comments, post: @post %>
    </div>
    <%= render "comments/form" %>
  </div>
</div>

app/views/posts/upvote.js.erb
$('.like').bind('ajax:success', function() {

    $('.like_count-<%= @post.id %>').text(<%= @post.get_upvotes.size%>);
    $('.dislike_count-<%= @post.id %>').text(<%= @post.get_downvotes.size%>);
    <%= add_gritter("_", title: "Post Liked", sticky: false, time: 1800, image: :success) %>
});